---
# install mariadb-server
- name: Install mariadb
  yum: pkg={{item}} state=latest
  with_items:
  - mariadb-server
  - php-mysql
  - mariadb
  - MySQL-python
# start mariadb-server
- name: Ensure mariadb is running
  service: name=mariadb state=started enabled=true
# mysql_secure_installation
- name: Sets the root password 
  mysql_user: user=root password="{{ mysql_root_password }}" host=localhost
- name: Copy the my.cnf
  copy: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
- name: delete anonymous MySQL server user for {{ ansible_hostname }}
  action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" state="absent"
- name: remove the MySQL test database
  action: mysql_db db=test state=absent
